// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFE1y7PyKUgIAQ-wJvrIAMXAYsl1CHJM',
    appId: '1:479064744416:web:f5ba001cb97f65eb8d4b85',
    messagingSenderId: '479064744416',
    projectId: 'foursquare-16e29',
    authDomain: 'foursquare-16e29.firebaseapp.com',
    storageBucket: 'foursquare-16e29.firebasestorage.app',
    measurementId: 'G-3YVXZFFQ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6eV5geDvFpoRqr1lYJr5SjtnKM0ZzP4c',
    appId: '1:479064744416:android:b74d722e9c3405488d4b85',
    messagingSenderId: '479064744416',
    projectId: 'foursquare-16e29',
    storageBucket: 'foursquare-16e29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3myKuFhlULSkAMrXQuZURDxv-byc2788',
    appId: '1:479064744416:ios:6c87030c763ec57c8d4b85',
    messagingSenderId: '479064744416',
    projectId: 'foursquare-16e29',
    storageBucket: 'foursquare-16e29.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3myKuFhlULSkAMrXQuZURDxv-byc2788',
    appId: '1:479064744416:ios:6c87030c763ec57c8d4b85',
    messagingSenderId: '479064744416',
    projectId: 'foursquare-16e29',
    storageBucket: 'foursquare-16e29.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWFE1y7PyKUgIAQ-wJvrIAMXAYsl1CHJM',
    appId: '1:479064744416:web:0328c332b6bd13c68d4b85',
    messagingSenderId: '479064744416',
    projectId: 'foursquare-16e29',
    authDomain: 'foursquare-16e29.firebaseapp.com',
    storageBucket: 'foursquare-16e29.firebasestorage.app',
    measurementId: 'G-FWWHY96BNX',
  );
}
